import React from "react";
import FilterSidebar from "./components/FilterSideBar";
import ProductGrid from "./components/ProductsGrid";
import { products } from "@/constants";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Products",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div className="container section">
      <h1 className="sectionTitle mt-5">Our Collection</h1>
      <div className="flex flex-col lg:flex-row gap-8">
        <FilterSidebar />
        <ProductGrid products={products} />
      </div>
    </div>
  );
};

export default page;
