import type { Metadata } from "next";
import { Changa } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shard/Navbar";
import Footer from "@/components/shard/Footer";
import ReduxProvider from "./ReduxProvider";
import { Toaster } from "@/components/ui/toaster";

const geistSans = Changa({
  variable: "--font-cairo-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "E-commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} antialiased`}>
        <ReduxProvider>
          <Navbar />
          {children}
          <Toaster />
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}

// suppressHydrationWarning;
